{% set name = "sorcha" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dirac-institute/sorcha/archive/v{{ version }}.tar.gz
  # curl -L https://github.com/dirac-institute/sorcha/archive/v0.9.0.tar.gz | openssl sha256
  sha256: c32a1c4a30b39dcfe7f7af8c4f452a7c667cb256804419556b35bb30c77a4d01
#  path: /Users/mjuric/projects/github.com/mjuric/sorcha

build:
  entry_points:
    - sorcha = sorcha_cmdline.main:main
    - sorcha-run = sorcha_cmdline.run:main
    - sorcha-init = sorcha_cmdline.init:main
    - sorcha-demo = sorcha_cmdline.demo:main
    - sorcha-outputs = sorcha_cmdline.outputs:main
    - sorcha-boostrap = sorcha_cmdline.bootstrap:main

  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=62
    - setuptools-scm >=7.0
    - pip
  run:
    - python >=3.8
    - numpy
    - pandas >=2.0
    - astropy
    - matplotlib-base
    - sbpy
    - pytables
    - spiceypy
    - healpy
    - assist
    - rebound
    - pooch
    - tqdm
    - numba

test:
  imports:
    - sorcha
    - sorcha_cmdline
  commands:
    - pip check
    - sorcha --help
    - sorcha run --help
    - sorcha init --help
    - sorcha demo --help
    - sorcha outputs --help
    - sorcha bootstrap --help
    - bash -x quicktest.sh
  requires:
    - pip
  files:
    - quicktest.sh

about:
  home: https://github.com/dirac-institute/sorcha
  summary: The survey simulator post processing code for the LSST
  license: BSD-3-Clause AND GPL-3.0-only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - drewoldag
    - mschwamb
    - mjuric
