{% set name = "sorcha" %}
{% set version = "0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sorcha-{{ version }}.tar.gz
  sha256: e7ca738586967cdee99a7aa32c096017dbc6bfc124e5895dc9a2be2c0660e16a

build:
  entry_points:
    - sorcha = sorcha.sorcha:main
    - makeConfigOIF = sorcha.utilities.makeConfigOIF:main
    - makeConfigSorcha = sorcha.utilities.makeConfigPP:main
    - makeMultiConfigOIF = sorcha.utilities.makeMultiConfigOIF:main
    - makeSLURMscript = sorcha.utilities.makeSLURMscript:main
    - createResultsSQLDatabase = sorcha.utilities.createResultsSQLDatabase:main
    - createTemporaryDatabases = sorcha.utilities.createTemporaryDatabases:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=62
    - setuptools-scm >=6.2
    - pytest-runner
    - pip
  run:
    - python >=3.8
    - numpy ==1.24.3
    - pandas
    - scipy
    - astropy
    - matplotlib-base
    - sbpy
    - pytables

test:
  imports:
    - sorcha
  commands:
    - pip check
    - sorcha --help
    - makeConfigOIF --help
    - makeConfigSorcha --help
    - makeMultiConfigOIF --help
    - makeSLURMscript --help
    - createResultsSQLDatabase --help
    - createTemporaryDatabases --help
  requires:
    - pip

about:
  home: https://github.com/lsst-sssc/lsstcomet
  summary: The survey simulator post processing code for the LSST
  dev_url: https://github.com/dirac-institute/survey_simulator_post_processing
  license: MIT AND GPL-3.0
  license_file:
    - LICENSE.txt
    - src/sorcha/lsstcomet/LICENSE

extra:
  recipe-maintainers:
    - drewoldag
    - mschwamb
