{% set name = "sorcha" %}
{% set version = "0.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dirac-institute/sorcha/archive/{{ version }}.tar.gz
  sha256: 8f93eb61976f39ac424f118f7881746b1d1b1e03f7f77dc03c30aad615d4185d
#   path: /Users/mjuric/projects/github.com/mjuric/sorcha

build:
  entry_points:
    - sorcha = sorcha.sorcha:main
    - makeConfigSorcha = sorcha.utilities.makeConfigPP:main
    - makeSLURMscript = sorcha.utilities.makeSLURMscript:main
    - createResultsSQLDatabase = sorcha.utilities.createResultsSQLDatabase:main
    - bootstrap_sorcha_data_files = sorcha.utilities.retrieve_ephemeris_data_files:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=62
    - setuptools-scm >=7.0
    - pip
  run:
    - python >=3.8
    - numpy
    - pandas >=2.0
    - astropy
    - matplotlib-base
    - sbpy
    - pytables
    - spiceypy
    - healpy
    - assist
    - rebound
    - pooch
    - tqdm
    - numba

test:
  imports:
    - sorcha
  commands:
    - pip check
    - sorcha --help
    - makeConfigSorcha --help
    - makeSLURMscript --help
    - createResultsSQLDatabase --help
    - bootstrap_sorcha_data_files --help
    - bash -x ./demo/quicktest.sh
  requires:
    - pip
  source_files:
    - demo/quicktest.sh
    - data/detectors_corners.csv
    - demo/baseline_v2.0_1yr.db
    - demo/sorcha_config_demo.ini
    - demo/sspp_testset_colours.txt
    - demo/sspp_testset_orbits.des

about:
  home: https://github.com/dirac-institute/sorcha
  summary: The survey simulator post processing code for the LSST
  license: BSD-3-Clause AND GPL-3.0-only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - drewoldag
    - mschwamb
    - mjuric
